name: Ethan Czahor
markdown: kramdown
kramdown:
  coderay_line_numbers: nil
  input: GFM
  syntax_highlighter: rouge
permalink: /:year/:month/:title
timezone: America/New_York
images_folder: /images/
gems:
  - jekyll-sitemap
